name: Docker

on:
  push:
    branches: [ marine ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: "Cache docker build"
      uses: actions/cache@v2
      id: cache-docker
      with:
        path: '/var/lib/docker/'
        key: 'constant-because-docker-handles-cache'

    - name: "Build docker image"
      run: docker build -t marine-core .


    - uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        # TODO: Check if can change docker prefix
        repository: domerd/marine-core
        tag_with_ref: true
